# Koyeb configuration file for advanced deployment settings
# This file is optional but provides more control over the deployment

name: rubik-master-backend

services:
  - name: api
    type: docker
    docker:
      dockerfile: backend/Dockerfile
    instance_type: nano
    regions:
      - sin  # Singapore (closest to Vietnam)
    ports:
      - port: 8000
        protocol: http
    env:
      - name: PORT
        value: "8000"
      - name: PYTHONPATH
        value: "/app"
    health_checks:
      - path: /health
        port: 8000
        protocol: http
        initial_delay_seconds: 30
        timeout_seconds: 5
        interval_seconds: 30
        failure_threshold: 3
    scaling:
      min: 1
      max: 3  # Auto-scale up to 3 instances under load
    resources:
      memory: 512Mi  # 512MB RAM
      cpu: "0.5"     # 0.5 CPU cores